name: children
description: Filter all non-null values in a Dart list.
version: 1.0.0
homepage: https://github.com/Gerhut/children
author: George Cheng <Gerhut@GMail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
