name: children
version: 1.1.0
description: Filter out all non-widgets from an iterable, used in `children` parameter of multi-child layout widgets.
author: George Cheng <Gerhut@GMail.com>
homepage: https://github.com/Gerhut/children

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.5.0
